### ISSUE TITLE
Use indexing into [row, col] instead of [row][col]

### ISSUE THREAD

**Issue by Tobias-Fischer** [jhavl/robotacademy-code#16]
@Tjeard0  this is the case in quite a few Python snippets

**Comment by Tjeard-van-Oort** [comment]
Ah im very sorry I will go update that and close the comment when I am finished!

**Comment by Tjeard-van-Oort** [comment]
When testing using [row, col] instead of [row][col] i get the following error TypeError: list indices must be integers or slices, not tuple

this occurs only in the video: region-features

All other videos that were using [row][col] should be updated now
