### ISSUE TITLE
Region features video should draw ellipse, not circle

### ISSUE THREAD

**Issue by Tobias-Fischer** [jhavl/robotacademy-code#19]
https://robotacademy.net.au/masterclass/feature-extraction/?lesson=695

**Comment by Tobias-Fischer** [comment]
It's defined in: https://github.com/bdaiinstitute/spatialmath-python/blob/07c6f62460030fd2c4f45112611e783abfbd8e4f/spatialmath/base/graphics.py#L820

**Comment by Tjeard-van-Oort** [comment]
Ah I was having issues with the plot function earlier which is why I was
using the circle, I'll try again tonight to get it up and running correctly!

**Comment by Tobias-Fischer** [comment]
See also https://github.com/petercorke/RVC3-python/blob/main/notebooks/chap12.ipynb (Figure 12.11 in the book)

**Comment by Tjeard-van-Oort** [comment]
Ah perfect, I had not seen that before so it will definitely help, thank
you!

**Comment by Tjeard-van-Oort** [comment]
This should be added in now with the correct functionality, I had some issues with it not displaying correctly on my system (tested both in a normal python and jupyter notebook) but it was working in the python notebook on google colab and I have made sure that the ellipses are being plotted correctly corresponding to the sharks in the image.
