### ISSUE TITLE
Many videos do not contain a code session, but still references to code

### ISSUE THREAD

**Issue by Tobias-Fischer** [jhavl/robotacademy-code#22]
Ideally we should add simple code snippets to those as well, see e.g. https://robotacademy.net.au/masterclass/spatial-operators/?lesson=678 - this way it's easy to see which function to use in other toolboxes.

**Comment by Tjeard-van-Oort** [comment]
Ah I'm very sorry, I had written these down to add code in for them but had completely forgotten about it. There should be 7 videos in total being:

Planar Homography *
Separating Intensity and Color *
Mathematical Morphology *
Rank Filtering *
kernels
Inverse Tangent function
Summary of digital images

I will make sure to complete those soon!

**Comment by Tobias-Fischer** [comment]
Please also note that you currently push to the wrong (non main) branch.

**Comment by Tjeard-van-Oort** [comment]
Yeah I still have been receiving errors when trying to use the main branch.
I can try again tonight and I'll link the error I get.

**Comment by Tjeard-van-Oort** [comment]
This is the issue I keep running into when attempting to upload directly to the main branch. 

![Capture](https://github.com/jhavl/robotacademy-code/assets/10625910/f3b44fbe-a394-4901-85ca-e91071686c69)

**Comment by Tjeard-van-Oort** [comment]
Sorry for the large delay in me getting these done, I have been moving houses and it has been taking up significantly more time than I had wanted. 

All of these videos should now have code snippets for rvc1, rvc2, mathworks when applicable and python
