### ISSUE TITLE
MathWorks Issues *In progress, will continue updating*

### ISSUE THREAD

**Issue by Tjeard-van-Oort** [jhavl/robotacademy-code#4]
**for same files in mathworks inverse kinematics issue** 
 no equivalent way to the robotics system toolbox to specify "r,rd,ld" (if it should be right handed, left handed etc...). Will comment in the file

**Analyzing a very simple 1- joint robot arm, Analyzing a very simple 2-joint planar robot arm, Analyzing a very simple 3-joint planar robot arm, Analyzing a robot arm that moves in 3D, Rigid-Body Dynamics:** Symbolics don't work with the MathWorks functions

**Analyzing a very simple 1- joint robot arm, Analyzing a very simple 2-joint planar robot arm, Analyzing a very simple 3-joint planar robot arm, danavit-hartenberg notation, Redundant robots, Velocity Ellipse in 2D, Jacobian and number of robot joints, Forces acting on robot links, Rigid body dynamics, Gravity and payload, inertia and acceleration coupling, velocity coupling, forces acting on robot links:** No simple method for generating the planar arms or the 20 joint arm, this could be written up as a separate library function however using the rigid body tree modeling method for MathWorks. 

**Base and tool transforms:** Unable to find method for translating the base of the robot, should be a quick fix if the function is found for this.

**Forward Dynamics:** No equivalent way to simulate collapse under gravity, possible to write up a function for this however

**The image jacobian:** cannot find method for image jacobians for MathWorks, it seems their library wasn't really meant for this kind of stuff, a question thread on the mathworks website for it points to peters toolbox instead

### **coordinate format update for mathworks files**

Setting the robot dataformat to 'row' using eg. `p560.DataFormat = 'row';` allows for standard arrays to be used to set the coordinates, will update files with this to simplify

### **Minor:**

** joint interpolated motion:** Unable to display animations with the show robot function

**Joint interpolated motion, cartesian interpolated motion:** Unable to locate the qplot equivalent function for MathWorks, a separate function could be written up for this most likely

**Hit and Miss Transform:** No triple point function for MathWorks, a function could be written up for this however

### **General Issues with Vision Toolbox:**

Need to use the computer vision toolbox as well as the image processing toolbox to achieve similar levels of capability

**Comment by petercorke** [comment]
@Tjeard0, it'd be easier if these were individual issues.  For each one please include the name of the folder on GH that it refers to.  These are all good points so please do this and we can then have a threaded discussion.

More generally:
* if a capability doesn't exist, eg. no symbolic variables in kinematics, just put that in a comment in the file
* please use `*` not `.*` to multiply MATLAB matrices and pose objects
* `se2(so2(q1, "theta"))` can be written much more concisely as `se2(q1, "theta")` 
* it's Denavit not Danavit

**Comment by Tjeard-van-Oort** [comment]
@petercorke I have added in the new issues for things that should be fixable. The rest of the things in this issue will be written up as comments in the files as it is relating to missing functionality.

I will go and do the same thing for the python issues as well!
